import { z } from 'zod';
import { nonEmptyStringSchema, objectIdSchema, timestampFieldsSchema } from './primitives.js';

export const AI_PROVIDERS = ['gemini', 'n8n', 'openai'] as const;

export const atividadeGeradaSchema = z.object({
  id: objectIdSchema,
  professorId: objectIdSchema,
  disciplinaId: objectIdSchema,
  turmaId: objectIdSchema.optional(),
  topic: nonEmptyStringSchema,
  objective: nonEmptyStringSchema,
  difficulty: z.enum(['easy', 'medium', 'hard']),
  content: nonEmptyStringSchema.describe('Markdown content generated by AI'),
  providerStats: z.object({
    provider: z.enum(AI_PROVIDERS),
    model: z.string(),
    latencyMs: z.number(),
    promptTokens: z.number().optional(),
    completionTokens: z.number().optional(),
  }),
  ...timestampFieldsSchema.shape,
});

export type AtividadeGerada = z.infer<typeof atividadeGeradaSchema>;

export const generateAtividadePayloadSchema = z.object({
  disciplinaId: objectIdSchema,
  turmaId: objectIdSchema.optional(),
  topic: nonEmptyStringSchema,
  objective: nonEmptyStringSchema,
  difficulty: z.enum(['easy', 'medium', 'hard']).default('medium'),
  providerOverride: z.enum(AI_PROVIDERS).optional(),
});

export type GenerateAtividadePayload = z.infer<typeof generateAtividadePayloadSchema>;

export const validacaoPedagogicaSchema = z.object({
  adequacaoTopic: z.number().min(0).max(10).describe('Score: matches the requested topic'),
  clareza: z.number().min(0).max(10).describe('Score: instructional clarity'),
  adequacaoIdade: z.number().min(0).max(10).describe('Score: age/level appropriateness'),
  feedback: z.string(),
  isAprovado: z.boolean(),
});

export type ValidacaoPedagogica = z.infer<typeof validacaoPedagogicaSchema>;
