import mongoose, { Schema } from 'mongoose';

// ─── Phone Subdocument ───────────────────────────────────────────────────────

const phoneSchema = new Schema(
  {
    phoneRaw: { type: String, required: true },
    phoneDigitsOnly: { type: String, required: true },
    phoneE164: { type: String, default: null },
    phoneIssue: {
      type: String,
      enum: [null, 'missing_area_code', 'incomplete_phone'],
      default: null,
    },
  },
  { _id: false }
);

// ─── Contact Subdocument (with stable _id) ───────────────────────────────────

const contactSchema = new Schema({
  role: { type: String, required: true },
  name: { type: String, required: true },
  phones: [phoneSchema],
  hasValidPhone: { type: Boolean, default: false },
  correctedPhone: {
    type: {
      phoneRaw: String,
      phoneDigitsOnly: String,
      phoneE164: String,
      phoneIssue: { type: String, default: null },
    },
    default: null,
  },
});
// _id is auto-generated by Mongoose for subdocuments with schema → stable identity

// ─── Timeline Entry Subdocument ──────────────────────────────────────────────

const timelineEntrySchema = new Schema({
  action: {
    type: String,
    required: true,
    enum: [
      'CASE_CREATED',
      'STATUS_CHANGED',
      'CONTACT_CORRECTED',
      'MESSAGE_PREPARED',
      'WHATSAPP_OPENED',
      'CONTACT_ATTEMPT_CONFIRMED',
      'RESPONSE_RECEIVED',
      'ATTACHMENT_UPLOADED',
      'CASE_RESOLVED',
      'IMPORT_SUPERSEDED',
    ],
  },
  channel: {
    type: String,
    enum: [null, 'whatsapp_manual', 'whatsapp_api', 'phone', 'in_person', 'sms'],
    default: null,
  },
  contactId: { type: Schema.Types.ObjectId, default: null },
  phoneUsed: { type: String, default: null },
  messageText: { type: String, default: null },
  waUrl: { type: String, default: null },
  previousStatus: { type: String, default: null },
  newStatus: { type: String, default: null },
  outcome: {
    type: String,
    enum: [null, 'sent', 'failed', 'no_answer', 'busy', 'answered', 'cancelled'],
    default: null,
  },
  responseText: { type: String, default: null },
  notes: { type: String, default: null },
  field: { type: String, default: null },
  oldValue: { type: String, default: null },
  newValue: { type: String, default: null },
  attachmentId: { type: Schema.Types.ObjectId, default: null },
  replacedByImportVersion: { type: Number, default: null },
  resolutionType: {
    type: String,
    enum: [null, 'justified', 'medical', 'family_issue', 'transportation', 'other', 'unjustified'],
    default: null,
  },
  justification: { type: String, default: null },
  createdBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
  createdAt: { type: Date, default: Date.now },
});

// ─── Attachment Metadata Subdocument ─────────────────────────────────────────

const attachmentSchema = new Schema({
  filename: { type: String, required: true },
  originalName: { type: String, required: true },
  mimeType: {
    type: String,
    required: true,
    enum: ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'],
  },
  size: { type: Number, required: true },
  sha256: { type: String, required: true },
  storagePath: { type: String, required: true },
  description: { type: String, default: null },
  uploadedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  uploadedAt: { type: Date, default: Date.now },
});

// ─── Main Case Schema ────────────────────────────────────────────────────────

const casoBuscaAtivaSchema = new Schema(
  {
    tenantId: {
      type: String,
      required: true,
      index: true,
    },
    importId: {
      type: Schema.Types.ObjectId,
      ref: 'AbsenceImport',
      required: true,
      index: true,
    },
    date: {
      type: Date,
      required: true,
    },

    // Student data
    alunoName: { type: String, required: true },
    normalizedAlunoName: { type: String, required: true, index: true },
    alunoId: {
      type: Schema.Types.ObjectId,
      ref: 'Aluno',
      default: null,
    },
    turmaName: { type: String, required: true },
    turmaId: {
      type: Schema.Types.ObjectId,
      ref: 'Turma',
      default: null,
    },

    // Contacts
    contacts: [contactSchema],

    // Flags from parser
    flags: {
      justified_in_source: { type: Boolean, default: false },
      possible_transfer: { type: Boolean, default: false },
      unmatched_aluno: { type: Boolean, default: false },
      ambiguous_aluno: { type: Boolean, default: false },
    },
    matchCandidates: [{ type: Schema.Types.ObjectId, ref: 'Aluno' }],
    observations: [{ type: String }],

    // Status lifecycle
    status: {
      type: String,
      required: true,
      enum: [
        'NOVO',
        'PENDENTE',
        'CONTATO_INICIADO',
        'AGUARDANDO_RESPOSTA',
        'RESPONDIDO',
        'JUSTIFICADO',
        'SEM_RETORNO',
        'REVISAO_ADMINISTRATIVA',
        'TELEFONE_INVALIDO',
        'ENCERRADO',
        'SUPERSEDED',
      ],
      default: 'NOVO',
      index: true,
    },

    // Timeline and attachments (embedded)
    timeline: [timelineEntrySchema],
    attachments: [attachmentSchema],
  },
  {
    timestamps: true,
  }
);

// Partial unique index: allows 1 active case + N SUPERSEDED for same aluno/date
casoBuscaAtivaSchema.index(
  { tenantId: 1, date: 1, alunoName: 1 },
  {
    unique: true,
    partialFilterExpression: { status: { $ne: 'SUPERSEDED' } },
  }
);

// Query performance indexes
casoBuscaAtivaSchema.index({ tenantId: 1, date: -1, status: 1 });
casoBuscaAtivaSchema.index({ tenantId: 1, alunoId: 1, date: -1 });

export const CasoBuscaAtivaModel = mongoose.model('CasoBuscaAtiva', casoBuscaAtivaSchema);
